### ISSUE TITLE
[Android] Logging in twice in one session causes a crash

### ISSUE THREAD

**Issue by wildseansy** [ianbattin/react-native-login-with-amazon#1]
Every time a call to `RNLoginWithAmazon.login()` is made, it registers a `new AuthorizeListener()` to the React native callback.  When login is successful or errors, this `AuthorizeListener` isn't unregistered, so the next time an `AuthorizeListener` event is propagated, it calls the old React Native callback again, and it crashes the app with the following error:

```
2019-10-30 12:21:03.726 16150-16439/com.myapp.debug E/AndroidRuntime: FATAL EXCEPTION: AmazonAuthorzationLibrary#1
    Process: com.myapp.debug, PID: 16150
    java.lang.RuntimeException: Illegal callback invocation from native module. This callback type
 only permits a single invocation from native code.
        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:25)
        at com.reactlibrary.RNLoginWithAmazonModule$1.onSuccess(RNLoginWithAmazonModule.java:63)
        at com.reactlibrary.RNLoginWithAmazonModule$1.onSuccess(RNLoginWithAmazonModule.java:53
```

Additionally a new `AuthorizeListener` is added with a new callback, each auth event propagates to every callback which causes problems

**Comment by SathishSaminathan** [comment]
@wildseansy bro can you show me the example?  

I am using 
"react-native": "0.61.5",
